/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import clases.VeterinariaFacade;
import clases.Cita;
import clases.Mascota;
import excepciones.CitaTraslapadaException;
import excepciones.MascotaNoEncontradaException;
import javax.swing.*;
import javax.swing.border.EmptyBorder;
import javax.swing.border.TitledBorder;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;

/**
 * Panel de agenda para la gestión de citas médicas.
 *
 * Permite buscar mascotas registradas, agendar nuevas citas y listar las
 * citas agendadas en una tabla.
 *
 * @author botel
 */
public class AgendaPanel extends javax.swing.JPanel {

    private JTextField mascotaIdField;
    private JButton buscarButton;
    private JTextArea mascotaInfoArea;
    private JSpinner fechaSpinner;
    private JSpinner horaSpinner;
    private JComboBox<String> servicioCombo;
    private JTextArea notasArea;
    private JButton agendarButton;
    private JButton limpiarButton;
    private JTable citasTable;
    private DefaultTableModel tableModel;
    private JLabel estadoLabel;
    private VeterinariaFacade veterinaria;
    private DateTimeFormatter dateFormatter;
    private DateTimeFormatter timeFormatter;

    /**
     * Crea el panel de agenda usando la fachada compartida de la veterinaria.
     *
     * @param veterinaria instancia compartida para acceder a mascotas y citas
     */
    public AgendaPanel(VeterinariaFacade veterinaria) {
        this.veterinaria = veterinaria;
        this.dateFormatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        this.timeFormatter = DateTimeFormatter.ofPattern("HH:mm");
        initComponents();
        setupUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        setLayout(new BorderLayout(10, 10));
        setBorder(new EmptyBorder(15, 15, 15, 15));
        setBackground(Color.WHITE);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Construye y organiza los componentes visuales del panel de agenda.
     */
    private void setupUI() {
        setLayout(new BorderLayout(10, 10));
        setBorder(new EmptyBorder(15, 15, 15, 15));
        setBackground(Color.WHITE);
        
        // Main panel with scroll
        JPanel mainPanel = new JPanel();
        mainPanel.setLayout(new BorderLayout(10, 10));
        mainPanel.setBackground(Color.WHITE);
        
        // Title
        JLabel titleLabel = new JLabel("📅 Agenda de Citas");
        titleLabel.setFont(new Font("Arial", Font.BOLD, 24));
        titleLabel.setForeground(new Color(41, 128, 185));
        mainPanel.add(titleLabel, BorderLayout.NORTH);
        
        // Container for all content
        JPanel contentContainer = new JPanel();
        contentContainer.setLayout(new BoxLayout(contentContainer, BoxLayout.Y_AXIS));
        contentContainer.setBackground(Color.WHITE);
        
        // Search Panel
        JPanel searchPanel = createSearchPanel();
        contentContainer.add(searchPanel);
        contentContainer.add(Box.createVerticalStrut(15));
        
        // Schedule Panel
        JPanel schedulePanel = createSchedulePanel();
        contentContainer.add(schedulePanel);
        contentContainer.add(Box.createVerticalStrut(15));
        
        // Table Panel
        JPanel tablePanel = createTablePanel();
        contentContainer.add(tablePanel);
        
        // Add to scroll pane
        JScrollPane scrollPane = new JScrollPane(contentContainer);
        scrollPane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);
        scrollPane.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
        mainPanel.add(scrollPane, BorderLayout.CENTER);
        
        add(mainPanel, BorderLayout.CENTER);
    }
    
    /**
     * Crea el panel de búsqueda para encontrar mascotas por ID.
     *
     * @return el panel de búsqueda con campos y resultados
     */
    private JPanel createSearchPanel() {
        JPanel panel = new JPanel();
        panel.setLayout(new GridBagLayout());
        panel.setBackground(Color.WHITE);
        panel.setBorder(new TitledBorder(
            BorderFactory.createLineBorder(new Color(41, 128, 185), 2),
            "Buscar Mascota",
            TitledBorder.LEFT,
            TitledBorder.TOP,
            new Font("Arial", Font.BOLD, 13),
            new Color(41, 128, 185)
        ));
        
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.insets = new Insets(10, 10, 10, 10);
        gbc.fill = GridBagConstraints.HORIZONTAL;
        
        // ID input
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 0.15;
        JLabel idLabel = new JLabel("ID Mascota:");
        idLabel.setFont(new Font("Arial", Font.BOLD, 11));
        panel.add(idLabel, gbc);
        
        gbc.gridx = 1;
        gbc.weightx = 0.3;
        mascotaIdField = new JTextField(15);
        mascotaIdField.setFont(new Font("Arial", Font.PLAIN, 11));
        mascotaIdField.setPreferredSize(new Dimension(150, 28));
        panel.add(mascotaIdField, gbc);
        
        // Search button
        gbc.gridx = 2;
        gbc.weightx = 0.1;
        buscarButton = new JButton("🔍 Buscar");
        buscarButton.setBackground(new Color(41, 128, 185));
        buscarButton.setForeground(Color.WHITE);
        buscarButton.setFocusPainted(false);
        buscarButton.setFont(new Font("Arial", Font.BOLD, 11));
        buscarButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        buscarButton.setPreferredSize(new Dimension(100, 28));
        buscarButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                buscarMascota();
            }
        });
        panel.add(buscarButton, gbc);
        
        // Status label
        gbc.gridx = 3;
        gbc.weightx = 0.45;
        estadoLabel = new JLabel("Esperando búsqueda...");
        estadoLabel.setFont(new Font("Arial", Font.ITALIC, 11));
        estadoLabel.setForeground(new Color(100, 100, 100));
        panel.add(estadoLabel, gbc);
        
        // Info area
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.gridwidth = 4;
        gbc.weightx = 1.0;
        gbc.weighty = 0.3;
        gbc.fill = GridBagConstraints.BOTH;
        mascotaInfoArea = new JTextArea(4, 50);
        mascotaInfoArea.setFont(new Font("Arial", Font.PLAIN, 10));
        mascotaInfoArea.setEditable(false);
        mascotaInfoArea.setBackground(new Color(240, 250, 255));
        mascotaInfoArea.setLineWrap(true);
        mascotaInfoArea.setWrapStyleWord(true);
        mascotaInfoArea.setBorder(BorderFactory.createLineBorder(new Color(200, 200, 200), 1));
        JScrollPane infoScroll = new JScrollPane(mascotaInfoArea);
        infoScroll.setPreferredSize(new Dimension(0, 100));
        panel.add(infoScroll, gbc);
        
        return panel;
    }
    
    /**
     * Crea el panel para ingresar los datos de una nueva cita.
     *
     * @return el panel de agendamiento de citas
     */
    private JPanel createSchedulePanel() {
        JPanel panel = new JPanel();
        panel.setLayout(new GridBagLayout());
        panel.setBackground(Color.WHITE);
        panel.setBorder(new TitledBorder(
            BorderFactory.createLineBorder(new Color(41, 128, 185), 2),
            "Agendar Cita",
            TitledBorder.LEFT,
            TitledBorder.TOP,
            new Font("Arial", Font.BOLD, 13),
            new Color(41, 128, 185)
        ));
        
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.insets = new Insets(10, 10, 10, 10);
        gbc.fill = GridBagConstraints.HORIZONTAL;
        
        // Row 0: Date and Time
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 0.15;
        JLabel fechaLabel = new JLabel("Fecha:");
        fechaLabel.setFont(new Font("Arial", Font.BOLD, 11));
        panel.add(fechaLabel, gbc);
        
        gbc.gridx = 1;
        gbc.weightx = 0.25;
        fechaSpinner = new JSpinner(new SpinnerDateModel());
        JSpinner.DateEditor dateEditor = new JSpinner.DateEditor(fechaSpinner, "dd/MM/yyyy");
        fechaSpinner.setEditor(dateEditor);
        fechaSpinner.setPreferredSize(new Dimension(130, 28));
        panel.add(fechaSpinner, gbc);
        
        gbc.gridx = 2;
        gbc.weightx = 0.1;
        JLabel horaLabel = new JLabel("Hora:");
        horaLabel.setFont(new Font("Arial", Font.BOLD, 11));
        panel.add(horaLabel, gbc);
        
        gbc.gridx = 3;
        gbc.weightx = 0.2;
        horaSpinner = new JSpinner(new SpinnerDateModel());
        JSpinner.DateEditor timeEditor = new JSpinner.DateEditor(horaSpinner, "HH:mm");
        horaSpinner.setEditor(timeEditor);
        horaSpinner.setPreferredSize(new Dimension(100, 28));
        panel.add(horaSpinner, gbc);
        
        // Row 1: Servicio
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weightx = 0.15;
        JLabel servicioLabel = new JLabel("Servicio:");
        servicioLabel.setFont(new Font("Arial", Font.BOLD, 11));
        panel.add(servicioLabel, gbc);
        
        gbc.gridx = 1;
        gbc.gridwidth = 3;
        gbc.weightx = 0.85;
        servicioCombo = new JComboBox<>(new String[]{
            "Consulta General",
            "Vacunación",
            "Limpieza de Dientes",
            "Cirugía",
            "Baño y Peluquería",
            "Otro"
        });
        servicioCombo.setFont(new Font("Arial", Font.PLAIN, 11));
        servicioCombo.setPreferredSize(new Dimension(300, 28));
        panel.add(servicioCombo, gbc);
        gbc.gridwidth = 1;
        
        // Row 2: Notas
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.weightx = 0.15;
        gbc.anchor = GridBagConstraints.NORTH;
        JLabel notasLabel = new JLabel("Notas:");
        notasLabel.setFont(new Font("Arial", Font.BOLD, 11));
        panel.add(notasLabel, gbc);
        
        gbc.gridx = 1;
        gbc.gridwidth = 3;
        gbc.weightx = 0.85;
        gbc.weighty = 0.3;
        gbc.fill = GridBagConstraints.BOTH;
        notasArea = new JTextArea(3, 50);
        notasArea.setFont(new Font("Arial", Font.PLAIN, 11));
        notasArea.setLineWrap(true);
        notasArea.setWrapStyleWord(true);
        notasArea.setBorder(BorderFactory.createLineBorder(new Color(200, 200, 200), 1));
        JScrollPane notasScroll = new JScrollPane(notasArea);
        notasScroll.setPreferredSize(new Dimension(0, 80));
        panel.add(notasScroll, gbc);
        gbc.gridwidth = 1;
        gbc.weighty = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.anchor = GridBagConstraints.WEST;
        
        // Row 3: Buttons
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.gridwidth = 4;
        gbc.weightx = 1.0;
        JPanel buttonPanel = new JPanel();
        buttonPanel.setBackground(Color.WHITE);
        buttonPanel.setLayout(new FlowLayout(FlowLayout.RIGHT, 8, 0));
        
        agendarButton = new JButton("📅 Agendar Cita");
        agendarButton.setBackground(new Color(39, 174, 96));
        agendarButton.setForeground(Color.WHITE);
        agendarButton.setFocusPainted(false);
        agendarButton.setFont(new Font("Arial", Font.BOLD, 11));
        agendarButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        agendarButton.setPreferredSize(new Dimension(130, 32));
        agendarButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                agendarCita();
            }
        });
        buttonPanel.add(agendarButton);
        
        limpiarButton = new JButton("🔄 Limpiar");
        limpiarButton.setBackground(new Color(149, 165, 166));
        limpiarButton.setForeground(Color.WHITE);
        limpiarButton.setFocusPainted(false);
        limpiarButton.setFont(new Font("Arial", Font.BOLD, 11));
        limpiarButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        limpiarButton.setPreferredSize(new Dimension(100, 32));
        limpiarButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                limpiarFormulario();
            }
        });
        buttonPanel.add(limpiarButton);
        
        panel.add(buttonPanel, gbc);
        
        return panel;
    }
    
    /**
     * Crea el panel con la tabla que muestra las citas agendadas.
     *
     * @return el panel de lista de citas
     */
    private JPanel createTablePanel() {
        JPanel panel = new JPanel();
        panel.setLayout(new BorderLayout());
        panel.setBackground(Color.WHITE);
        panel.setBorder(new TitledBorder(
            BorderFactory.createLineBorder(new Color(41, 128, 185), 2),
            "Citas Agendadas",
            TitledBorder.LEFT,
            TitledBorder.TOP,
            new Font("Arial", Font.BOLD, 13),
            new Color(41, 128, 185)
        ));
        panel.setPreferredSize(new Dimension(0, 280));
        
        // Create table
        String[] columnNames = {"ID Mascota", "Nombre Mascota", "Fecha", "Hora", "Servicio", "Estado"};
        tableModel = new DefaultTableModel(columnNames, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        citasTable = new JTable(tableModel);
        citasTable.setRowHeight(30);
        citasTable.setFont(new Font("Arial", Font.PLAIN, 11));
        citasTable.getTableHeader().setFont(new Font("Arial", Font.BOLD, 12));
        citasTable.getTableHeader().setBackground(new Color(41, 128, 185));
        citasTable.getTableHeader().setForeground(Color.WHITE);
        citasTable.getTableHeader().setPreferredSize(new Dimension(0, 35));
        citasTable.setSelectionBackground(new Color(174, 214, 241));
        citasTable.setSelectionForeground(Color.BLACK);
        citasTable.setGridColor(new Color(220, 220, 220));
        citasTable.setShowGrid(true);
        
        // Set column widths
        citasTable.getColumnModel().getColumn(0).setPreferredWidth(80);
        citasTable.getColumnModel().getColumn(1).setPreferredWidth(120);
        citasTable.getColumnModel().getColumn(2).setPreferredWidth(90);
        citasTable.getColumnModel().getColumn(3).setPreferredWidth(70);
        citasTable.getColumnModel().getColumn(4).setPreferredWidth(150);
        citasTable.getColumnModel().getColumn(5).setPreferredWidth(80);
        
        JScrollPane tableScroll = new JScrollPane(citasTable);
        tableScroll.setPreferredSize(new Dimension(0, 200));
        panel.add(tableScroll, BorderLayout.CENTER);
        
        return panel;
    }
    
    /**
     * Busca una mascota en la fachada a partir de su ID y actualiza la interfaz.
     */
    private void buscarMascota() {
        String id = mascotaIdField.getText().trim();
        
        if (id.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor ingresa un ID de mascota.",
                "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        try {
            Mascota mascota = veterinaria.buscarMascota(id);
            String info = "Mascota Encontrada:\n" +
                         "ID: " + mascota.getId() + "\n" +
                         "Nombre: " + mascota.getNombre() + "\n" +
                         "Edad: " + mascota.getEdad() + " años\n" +
                         "Dueño: " + mascota.getDueno().getNombre() + "\n" +
                         "Teléfono: " + mascota.getDueno().getTelefono() + "\n" +
                         "Cuidados: " + mascota.obtenerCuidadosBasicos();
            mascotaInfoArea.setText(info);
            estadoLabel.setText("✓ Mascota encontrada");
            estadoLabel.setForeground(new Color(39, 174, 96));
        } catch (MascotaNoEncontradaException e) {
            mascotaInfoArea.setText("Mascota no encontrada.");
            estadoLabel.setText("✗ Mascota no encontrada");
            estadoLabel.setForeground(new Color(220, 53, 69));
        }
    }
    
    /**
     * Agrega una nueva cita al sistema y la muestra en la tabla.
     */
    private void agendarCita() {
        String mascotaId = mascotaIdField.getText().trim();
        
        if (mascotaId.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor busca una mascota primero.",
                "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        try {
            Mascota mascota = veterinaria.buscarMascota(mascotaId);
            String servicio = (String) servicioCombo.getSelectedItem();
            
            java.time.LocalDateTime fechaHora = java.time.LocalDateTime.now();
            Cita cita = new Cita(1, fechaHora, mascota, servicio);
            veterinaria.agendarCita(cita);
            
            tableModel.addRow(new Object[]{
                mascota.getId(),
                mascota.getNombre(),
                "01/01/2026",
                "10:00",
                servicio,
                "Pendiente"
            });
            
            JOptionPane.showMessageDialog(this, "Cita agendada exitosamente.",
                "Éxito", JOptionPane.INFORMATION_MESSAGE);
            limpiarFormulario();
        } catch (MascotaNoEncontradaException e) {
            JOptionPane.showMessageDialog(this, "Mascota no encontrada: " + e.getMessage(),
                "Error", JOptionPane.ERROR_MESSAGE);
        } catch (CitaTraslapadaException e) {
            JOptionPane.showMessageDialog(this, "No se puede agendar la cita: " + e.getMessage(),
                "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al agendar la cita: " + e.getMessage(),
                "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    /**
     * Limpia los campos del formulario de búsqueda y agendamiento.
     */
    private void limpiarFormulario() {
        mascotaIdField.setText("");
        mascotaInfoArea.setText("");
        servicioCombo.setSelectedIndex(0);
        notasArea.setText("");
        estadoLabel.setText("Esperando búsqueda...");
        estadoLabel.setForeground(new Color(100, 100, 100));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
