/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import clases.VeterinariaFacade;
import javax.swing.*;
import javax.swing.border.EmptyBorder;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 * Ventana principal de la aplicación veterinaria.
 *
 * Contiene la navegación entre el panel de registro y el panel de agenda,
 * además de manejar la instancia compartida de {@link VeterinariaFacade}.
 *
 * @author botel
 */
public class MainFrame extends javax.swing.JFrame {

    private JPanel headerPanel;
    private JLabel titleLabel;
    private JLabel subtitleLabel;
    private JPanel navigationPanel;
    private JButton registroButton;
    private JButton agendaButton;
    private JPanel contentPanel;
    private CardLayout cardLayout;
    private RegistroPanel registroPanel;
    private AgendaPanel agendaPanel;
    private VeterinariaFacade veterinaria;
    private JPanel footerPanel;
    private JLabel statusLabel;

    /**
     * Crea la ventana principal e inicializa los componentes visuales.
     */
    public MainFrame() {
        initComponents();
        setupUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Configura la interfaz de usuario principal y monta los paneles.
     *
     * Construye el header, el panel de navegación, el contenido con CardLayout
     * y el footer.
     */
    private void setupUI() {
        getContentPane().removeAll();
        getContentPane().setLayout(new BorderLayout(0, 0));
        
        // Header Panel
        headerPanel = createHeaderPanel();
        getContentPane().add(headerPanel, BorderLayout.NORTH);
        
        // Main content with navigation and central panel
        JPanel mainContentPanel = new JPanel();
        mainContentPanel.setLayout(new BorderLayout(0, 0));
        mainContentPanel.setBackground(Color.WHITE);
        
        // Navigation Panel
        navigationPanel = createNavigationPanel();
        mainContentPanel.add(navigationPanel, BorderLayout.WEST);
        
        // Shared data store for both panels
        veterinaria = new VeterinariaFacade();

        // Content Panel with CardLayout
        cardLayout = new CardLayout();
        contentPanel = new JPanel(cardLayout);
        contentPanel.setBackground(Color.WHITE);
        contentPanel.setPreferredSize(new Dimension(700, 500));
        
        registroPanel = new RegistroPanel(veterinaria);
        agendaPanel = new AgendaPanel(veterinaria);
        
        contentPanel.add(registroPanel, "Registro");
        contentPanel.add(agendaPanel, "Agenda");
        
        mainContentPanel.add(contentPanel, BorderLayout.CENTER);
        
        // Footer Panel
        footerPanel = createFooterPanel();
        
        // Add main content to frame
        getContentPane().add(mainContentPanel, BorderLayout.CENTER);
        getContentPane().add(footerPanel, BorderLayout.SOUTH);
        
        // Initialize button styles
        updateButtonStyles("Registro");
        
        revalidate();
        repaint();
    }
    
    /**
     * Crea el panel de encabezado con el título principal y el subtítulo.
     *
     * @return un panel configurado como header de la aplicación
     */
    private JPanel createHeaderPanel() {
        JPanel panel = new JPanel();
        panel.setLayout(new BorderLayout());
        panel.setBackground(new Color(41, 128, 185));
        panel.setBorder(new EmptyBorder(20, 30, 20, 30));
        panel.setPreferredSize(new Dimension(0, 120));
        
        JPanel titlePanel = new JPanel();
        titlePanel.setLayout(new BoxLayout(titlePanel, BoxLayout.Y_AXIS));
        titlePanel.setBackground(new Color(41, 128, 185));
        
        titleLabel = new JLabel("Veterinaria San Nicolás");
        titleLabel.setFont(new Font("Arial", Font.BOLD, 32));
        titleLabel.setForeground(Color.WHITE);
        
        subtitleLabel = new JLabel("Sistema de Gestión de Mascotas y Citas");
        subtitleLabel.setFont(new Font("Arial", Font.PLAIN, 14));
        subtitleLabel.setForeground(new Color(200, 220, 240));
        
        titlePanel.add(titleLabel);
        titlePanel.add(Box.createVerticalStrut(5));
        titlePanel.add(subtitleLabel);
        
        panel.add(titlePanel, BorderLayout.WEST);
        
        return panel;
    }
    
    /**
     * Crea el panel de navegación lateral con botones de acceso a los módulos.
     *
     * @return el panel de navegación completo
     */
    private JPanel createNavigationPanel() {
        JPanel panel = new JPanel();
        panel.setLayout(new BoxLayout(panel, BoxLayout.Y_AXIS));
        panel.setBackground(new Color(236, 240, 241));
        panel.setBorder(new EmptyBorder(20, 15, 20, 15));
        panel.setPreferredSize(new Dimension(180, 0));
        
        JLabel navLabel = new JLabel("MENÚ");
        navLabel.setFont(new Font("Arial", Font.BOLD, 12));
        navLabel.setForeground(new Color(41, 128, 185));
        panel.add(navLabel);
        panel.add(Box.createVerticalStrut(15));
        
        registroButton = createNavigationButton("📝 Registro de Mascotas");
        registroButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                cardLayout.show(contentPanel, "Registro");
                updateButtonStyles("Registro");
                statusLabel.setText("Módulo: Registro de Mascotas");
            }
        });
        panel.add(registroButton);
        panel.add(Box.createVerticalStrut(10));
        
        agendaButton = createNavigationButton("📅 Agenda de Citas");
        agendaButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                cardLayout.show(contentPanel, "Agenda");
                updateButtonStyles("Agenda");
                statusLabel.setText("Módulo: Agenda de Citas");
            }
        });
        panel.add(agendaButton);
        panel.add(Box.createVerticalStrut(20));
        
        // Separator
        JSeparator separator = new JSeparator();
        separator.setMaximumSize(new Dimension(150, 1));
        panel.add(separator);
        panel.add(Box.createVerticalStrut(15));
        
        // Info section
        JLabel infoLabel = new JLabel("INFORMACIÓN");
        infoLabel.setFont(new Font("Arial", Font.BOLD, 12));
        infoLabel.setForeground(new Color(41, 128, 185));
        panel.add(infoLabel);
        panel.add(Box.createVerticalStrut(10));
        
        JLabel phoneLabel = new JLabel("Teléfono:+52 622 XXX XXXX");
        phoneLabel.setFont(new Font("Arial", Font.PLAIN, 10));
        panel.add(phoneLabel);
        panel.add(Box.createVerticalStrut(10));
        
        JLabel emailLabel = new JLabel("Email:info@sannicolas.com");
        emailLabel.setFont(new Font("Arial", Font.PLAIN, 10));
        panel.add(emailLabel);
        
        panel.add(Box.createVerticalGlue());
        
        JButton exitButton = new JButton("Salir");
        exitButton.setMaximumSize(new Dimension(150, 35));
        exitButton.setBackground(new Color(220, 53, 69));
        exitButton.setForeground(Color.WHITE);
        exitButton.setFocusPainted(false);
        exitButton.setFont(new Font("Arial", Font.BOLD, 11));
        exitButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        exitButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                System.exit(0);
            }
        });
        panel.add(exitButton);
        
        return panel;
    }
    
    /**
     * Crea un botón de navegación con estilo consistente.
     *
     * @param text etiqueta del botón
     * @return el botón configurado
     */
    private JButton createNavigationButton(String text) {
        JButton button = new JButton(text);
        button.setMaximumSize(new Dimension(150, 40));
        button.setBackground(Color.WHITE);
        button.setForeground(new Color(41, 128, 185));
        button.setFocusPainted(false);
        button.setFont(new Font("Arial", Font.BOLD, 11));
        button.setBorder(BorderFactory.createLineBorder(new Color(41, 128, 185), 2));
        button.setCursor(new Cursor(Cursor.HAND_CURSOR));
        return button;
    }
    
    /**
     * Actualiza el estilo de los botones de navegación según el panel activo.
     *
     * @param activePanel nombre del panel que está visible
     */
    private void updateButtonStyles(String activePanel) {
        if (activePanel.equals("Registro")) {
            registroButton.setBackground(new Color(41, 128, 185));
            registroButton.setForeground(Color.WHITE);
            agendaButton.setBackground(Color.WHITE);
            agendaButton.setForeground(new Color(41, 128, 185));
        } else {
            agendaButton.setBackground(new Color(41, 128, 185));
            agendaButton.setForeground(Color.WHITE);
            registroButton.setBackground(Color.WHITE);
            registroButton.setForeground(new Color(41, 128, 185));
        }
    }
    
    /**
     * Crea el panel inferior con información de estado y versión.
     *
     * @return el panel de footer de la ventana principal
     */
    private JPanel createFooterPanel() {
        JPanel panel = new JPanel();
        panel.setLayout(new BorderLayout());
        panel.setBackground(new Color(52, 73, 94));
        panel.setBorder(new EmptyBorder(10, 20, 10, 20));
        panel.setPreferredSize(new Dimension(0, 50));
        
        statusLabel = new JLabel("Módulo: Registro de Mascotas");
        statusLabel.setFont(new Font("Arial", Font.PLAIN, 11));
        statusLabel.setForeground(Color.WHITE);
        
        JLabel versionLabel = new JLabel("Versión 1.0 - 2026");
        versionLabel.setFont(new Font("Arial", Font.PLAIN, 11));
        versionLabel.setForeground(new Color(189, 195, 199));
        
        panel.add(statusLabel, BorderLayout.WEST);
        panel.add(versionLabel, BorderLayout.EAST);
        
        return panel;
    }

    /**
     * Método principal generado por NetBeans para iniciar la ventana.
     *
     * @param args argumentos de línea de comandos (no utilizados)
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
