/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import clases.VeterinariaFacade;
import clases.Mascota;
import clases.Gato;
import clases.Perro;
import clases.Dueno;
import javax.swing.*;
import javax.swing.border.EmptyBorder;
import javax.swing.border.TitledBorder;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 * Panel de registro de mascotas para la veterinaria.
 *
 * Permite capturar datos de la mascota y su dueño, y mostrar las mascotas
 * registradas en una tabla.
 *
 * @author botel
 */
public class RegistroPanel extends javax.swing.JPanel {

    private JTextField nombreField;
    private JTextField idField;
    private JSpinner edadSpinner;
    private JComboBox<String> tipoMascotaCombo;
    private JTextField razaField;
    private JCheckBox domesticoCheckBox;
    private JTextField duenioNombreField;
    private JTextField duenioIdField;
    private JTextField duenioTelefonoField;
    private JButton guardarButton;
    private JButton limpiarButton;
    private JTable mascotasTable;
    private DefaultTableModel tableModel;
    private JTextArea detallesArea;
    private VeterinariaFacade veterinaria;

    /**
     * Crea el panel de registro utilizando la fachada compartida.
     *
     * @param veterinaria instancia compartida para registrar mascotas
     */
    public RegistroPanel(VeterinariaFacade veterinaria) {
        this.veterinaria = veterinaria;
        initComponents();
        setupUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        setLayout(new BorderLayout(10, 10));
        setBorder(new EmptyBorder(15, 15, 15, 15));
        setBackground(Color.WHITE);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Configura la interfaz del panel de registro, incluyendo formulario y tabla.
     */
    private void setupUI() {
        setLayout(new BorderLayout(10, 10));
        setBorder(new EmptyBorder(15, 15, 15, 15));
        setBackground(Color.WHITE);
        
        // Main panel with scroll
        JPanel mainPanel = new JPanel();
        mainPanel.setLayout(new BorderLayout(10, 10));
        mainPanel.setBackground(Color.WHITE);
        
        // Title
        JLabel titleLabel = new JLabel("📝 Registro de Mascotas");
        titleLabel.setFont(new Font("Arial", Font.BOLD, 24));
        titleLabel.setForeground(new Color(41, 128, 185));
        mainPanel.add(titleLabel, BorderLayout.NORTH);
        
        // Container for form and table
        JPanel contentContainer = new JPanel();
        contentContainer.setLayout(new BoxLayout(contentContainer, BoxLayout.Y_AXIS));
        contentContainer.setBackground(Color.WHITE);
        
        // Form Panel
        JPanel formPanel = createFormPanel();
        contentContainer.add(formPanel);
        contentContainer.add(Box.createVerticalStrut(20));
        
        // Table Panel
        JPanel tablePanel = createTablePanel();
        contentContainer.add(tablePanel);
        
        // Add to scroll pane
        JScrollPane scrollPane = new JScrollPane(contentContainer);
        scrollPane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);
        scrollPane.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
        mainPanel.add(scrollPane, BorderLayout.CENTER);
        
        add(mainPanel, BorderLayout.CENTER);
    }
    
    /**
     * Crea el panel de formulario para ingresar los datos de la mascota y del dueño.
     *
     * @return el panel que contiene los campos de registro
     */
    private JPanel createFormPanel() {
        JPanel panel = new JPanel();
        panel.setLayout(new GridBagLayout());
        panel.setBackground(Color.WHITE);
        panel.setBorder(new TitledBorder(
            BorderFactory.createLineBorder(new Color(41, 128, 185), 2),
            "Información de la Mascota",
            TitledBorder.LEFT,
            TitledBorder.TOP,
            new Font("Arial", Font.BOLD, 13),
            new Color(41, 128, 185)
        ));
        
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.insets = new Insets(10, 10, 10, 10);
        gbc.fill = GridBagConstraints.HORIZONTAL;
        
        // ===== MASCOTA INFO SECTION =====
        // Row 0: ID Mascota and Tipo
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 0.2;
        JLabel idLabel = new JLabel("ID Mascota:");
        idLabel.setFont(new Font("Arial", Font.BOLD, 11));
        panel.add(idLabel, gbc);
        
        gbc.gridx = 1;
        gbc.weightx = 0.3;
        idField = new JTextField(15);
        idField.setFont(new Font("Arial", Font.PLAIN, 11));
        idField.setPreferredSize(new Dimension(150, 28));
        panel.add(idField, gbc);
        
        gbc.gridx = 2;
        gbc.weightx = 0.15;
        JLabel tipoLabel = new JLabel("Tipo:");
        tipoLabel.setFont(new Font("Arial", Font.BOLD, 11));
        panel.add(tipoLabel, gbc);
        
        gbc.gridx = 3;
        gbc.weightx = 0.3;
        tipoMascotaCombo = new JComboBox<>(new String[]{"Perro", "Gato"});
        tipoMascotaCombo.setFont(new Font("Arial", Font.PLAIN, 11));
        tipoMascotaCombo.setPreferredSize(new Dimension(100, 28));
        tipoMascotaCombo.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                actualizarCamposSegunTipo();
            }
        });
        panel.add(tipoMascotaCombo, gbc);
        
        // Row 1: Nombre Mascota and Edad
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weightx = 0.2;
        JLabel nombreLabel = new JLabel("Nombre Mascota:");
        nombreLabel.setFont(new Font("Arial", Font.BOLD, 11));
        panel.add(nombreLabel, gbc);
        
        gbc.gridx = 1;
        gbc.weightx = 0.3;
        nombreField = new JTextField(15);
        nombreField.setFont(new Font("Arial", Font.PLAIN, 11));
        nombreField.setPreferredSize(new Dimension(150, 28));
        panel.add(nombreField, gbc);
        
        gbc.gridx = 2;
        gbc.weightx = 0.15;
        JLabel edadLabel = new JLabel("Edad (años):");
        edadLabel.setFont(new Font("Arial", Font.BOLD, 11));
        panel.add(edadLabel, gbc);
        
        gbc.gridx = 3;
        gbc.weightx = 0.3;
        edadSpinner = new JSpinner(new SpinnerNumberModel(1, 0, 50, 1));
        edadSpinner.setPreferredSize(new Dimension(100, 28));
        panel.add(edadSpinner, gbc);
        
        // Row 2: Raza (para perros) and Doméstico (para gatos)
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.weightx = 0.2;
        JLabel razaLabel = new JLabel("Raza/Característica:");
        razaLabel.setFont(new Font("Arial", Font.BOLD, 11));
        panel.add(razaLabel, gbc);
        
        gbc.gridx = 1;
        gbc.weightx = 0.3;
        razaField = new JTextField(15);
        razaField.setFont(new Font("Arial", Font.PLAIN, 11));
        razaField.setPreferredSize(new Dimension(150, 28));
        razaField.setToolTipText("Raza del perro o característica especial");
        panel.add(razaField, gbc);
        
        gbc.gridx = 2;
        gbc.weightx = 0.15;
        JLabel domesticoLabel = new JLabel("¿Doméstico?:");
        domesticoLabel.setFont(new Font("Arial", Font.BOLD, 11));
        panel.add(domesticoLabel, gbc);
        
        gbc.gridx = 3;
        gbc.weightx = 0.3;
        domesticoCheckBox = new JCheckBox("Sí");
        domesticoCheckBox.setBackground(Color.WHITE);
        domesticoCheckBox.setFont(new Font("Arial", Font.PLAIN, 11));
        domesticoCheckBox.setVisible(false);
        panel.add(domesticoCheckBox, gbc);
        
        // Separator
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.gridwidth = 4;
        gbc.insets = new Insets(15, 10, 15, 10);
        JSeparator separator = new JSeparator();
        panel.add(separator, gbc);
        gbc.gridwidth = 1;
        gbc.insets = new Insets(10, 10, 10, 10);
        
        // ===== DUEÑO INFO SECTION =====
        // Row 4: Dueño Info Title
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.gridwidth = 4;
        JLabel duenioTitle = new JLabel("Información del Dueño");
        duenioTitle.setFont(new Font("Arial", Font.BOLD, 12));
        duenioTitle.setForeground(new Color(41, 128, 185));
        panel.add(duenioTitle, gbc);
        gbc.gridwidth = 1;
        
        // Row 5: Dueño ID and Nombre
        gbc.gridx = 0;
        gbc.gridy = 5;
        gbc.weightx = 0.2;
        JLabel duenioIdLabel = new JLabel("ID Dueño:");
        duenioIdLabel.setFont(new Font("Arial", Font.BOLD, 11));
        panel.add(duenioIdLabel, gbc);
        
        gbc.gridx = 1;
        gbc.weightx = 0.3;
        duenioIdField = new JTextField(15);
        duenioIdField.setFont(new Font("Arial", Font.PLAIN, 11));
        duenioIdField.setPreferredSize(new Dimension(150, 28));
        panel.add(duenioIdField, gbc);
        
        gbc.gridx = 2;
        gbc.weightx = 0.15;
        JLabel duenioNombreLabel = new JLabel("Nombre Dueño:");
        duenioNombreLabel.setFont(new Font("Arial", Font.BOLD, 11));
        panel.add(duenioNombreLabel, gbc);
        
        gbc.gridx = 3;
        gbc.weightx = 0.3;
        duenioNombreField = new JTextField(15);
        duenioNombreField.setFont(new Font("Arial", Font.PLAIN, 11));
        duenioNombreField.setPreferredSize(new Dimension(150, 28));
        panel.add(duenioNombreField, gbc);
        
        // Row 6: Teléfono and Buttons
        gbc.gridx = 0;
        gbc.gridy = 6;
        gbc.weightx = 0.2;
        JLabel telefonoLabel = new JLabel("Teléfono Dueño:");
        telefonoLabel.setFont(new Font("Arial", Font.BOLD, 11));
        panel.add(telefonoLabel, gbc);
        
        gbc.gridx = 1;
        gbc.weightx = 0.3;
        duenioTelefonoField = new JTextField(15);
        duenioTelefonoField.setFont(new Font("Arial", Font.PLAIN, 11));
        duenioTelefonoField.setPreferredSize(new Dimension(150, 28));
        panel.add(duenioTelefonoField, gbc);
        
        gbc.gridx = 2;
        gbc.gridwidth = 2;
        gbc.weightx = 0.5;
        JPanel buttonPanel = new JPanel();
        buttonPanel.setBackground(Color.WHITE);
        buttonPanel.setLayout(new FlowLayout(FlowLayout.RIGHT, 8, 0));
        
        guardarButton = new JButton("💾 Guardar");
        guardarButton.setBackground(new Color(39, 174, 96));
        guardarButton.setForeground(Color.WHITE);
        guardarButton.setFocusPainted(false);
        guardarButton.setFont(new Font("Arial", Font.BOLD, 11));
        guardarButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        guardarButton.setPreferredSize(new Dimension(100, 32));
        guardarButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                guardarMascota();
            }
        });
        buttonPanel.add(guardarButton);
        
        limpiarButton = new JButton("🔄 Limpiar");
        limpiarButton.setBackground(new Color(149, 165, 166));
        limpiarButton.setForeground(Color.WHITE);
        limpiarButton.setFocusPainted(false);
        limpiarButton.setFont(new Font("Arial", Font.BOLD, 11));
        limpiarButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        limpiarButton.setPreferredSize(new Dimension(100, 32));
        limpiarButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                limpiarFormulario();
            }
        });
        buttonPanel.add(limpiarButton);
        
        panel.add(buttonPanel, gbc);
        gbc.gridwidth = 1;
        
        return panel;
    }
    
    /**
     * Crea el panel que muestra la tabla de mascotas registradas.
     *
     * @return el panel con la tabla de registros
     */
    private JPanel createTablePanel() {
        JPanel panel = new JPanel();
        panel.setLayout(new BorderLayout());
        panel.setBackground(Color.WHITE);
        panel.setBorder(new TitledBorder(
            BorderFactory.createLineBorder(new Color(41, 128, 185), 2),
            "Mascotas Registradas",
            TitledBorder.LEFT,
            TitledBorder.TOP,
            new Font("Arial", Font.BOLD, 13),
            new Color(41, 128, 185)
        ));
        panel.setPreferredSize(new Dimension(0, 300));
        
        // Create table
        String[] columnNames = {"ID", "Nombre", "Tipo", "Edad", "Dueño", "Teléfono"};
        tableModel = new DefaultTableModel(columnNames, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Make table non-editable
            }
        };
        
        mascotasTable = new JTable(tableModel);
        mascotasTable.setRowHeight(30);
        mascotasTable.setFont(new Font("Arial", Font.PLAIN, 11));
        mascotasTable.getTableHeader().setFont(new Font("Arial", Font.BOLD, 12));
        mascotasTable.getTableHeader().setBackground(new Color(41, 128, 185));
        mascotasTable.getTableHeader().setForeground(Color.WHITE);
        mascotasTable.getTableHeader().setPreferredSize(new Dimension(0, 35));
        mascotasTable.setSelectionBackground(new Color(174, 214, 241));
        mascotasTable.setSelectionForeground(Color.BLACK);
        mascotasTable.setGridColor(new Color(220, 220, 220));
        mascotasTable.setShowGrid(true);
        
        // Set column widths
        mascotasTable.getColumnModel().getColumn(0).setPreferredWidth(60);
        mascotasTable.getColumnModel().getColumn(1).setPreferredWidth(100);
        mascotasTable.getColumnModel().getColumn(2).setPreferredWidth(60);
        mascotasTable.getColumnModel().getColumn(3).setPreferredWidth(50);
        mascotasTable.getColumnModel().getColumn(4).setPreferredWidth(120);
        mascotasTable.getColumnModel().getColumn(5).setPreferredWidth(100);
        
        JScrollPane tableScroll = new JScrollPane(mascotasTable);
        tableScroll.setPreferredSize(new Dimension(0, 200));
        panel.add(tableScroll, BorderLayout.CENTER);
        
        return panel;
    }
    
    /**
     * Guarda la información de la mascota en la fachada veterinaria y añade la fila a la tabla.
     *
     * Valida los campos obligatorios, crea el objeto correspondiente y limpia
     * el formulario al terminar.
     */
    private void guardarMascota() {
        try {
            String id = idField.getText().trim();
            String nombre = nombreField.getText().trim();
            int edad = (Integer) edadSpinner.getValue();
            String tipo = (String) tipoMascotaCombo.getSelectedItem();
            String raza = razaField.getText().trim();
            boolean domestico = domesticoCheckBox.isSelected();
            
            String duenioId = duenioIdField.getText().trim();
            String duenioNombre = duenioNombreField.getText().trim();
            String duenioTelefono = duenioTelefonoField.getText().trim();
            
            // Validations
            if (id.isEmpty() || nombre.isEmpty() || duenioId.isEmpty() || duenioNombre.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Por favor, completa todos los campos requeridos.",
                    "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            // Create Dueno with 4 parameters (with empty address)
            Dueno dueno = new Dueno(duenioId, duenioNombre, duenioTelefono, "");
            
            // Create Mascota
            Mascota mascota;
            if (tipo.equals("Perro")) {
                if (raza.isEmpty()) {
                    raza = "Sin especificar";
                }
                mascota = new Perro(id, nombre, edad, dueno, raza);
            } else {
                mascota = new Gato(id, nombre, edad, dueno, domestico);
            }
            
            // Register mascota
            veterinaria.registrarMascota(mascota);
            
            // Add to table
            tableModel.addRow(new Object[]{
                id,
                nombre,
                tipo,
                edad,
                duenioNombre,
                duenioTelefono
            });
            
            // Show message
            JOptionPane.showMessageDialog(this, "Mascota registrada exitosamente.",
                "Éxito", JOptionPane.INFORMATION_MESSAGE);
            
            // Clear form
            limpiarFormulario();
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Error en los datos ingresados.",
                "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    /**
     * Actualiza la visibilidad de los campos del formulario según el tipo de mascota seleccionado.
     */
    private void actualizarCamposSegunTipo() {
        String tipo = (String) tipoMascotaCombo.getSelectedItem();
        if (tipo.equals("Perro")) {
            razaField.setVisible(true);
            domesticoCheckBox.setVisible(false);
        } else {
            razaField.setVisible(false);
            domesticoCheckBox.setVisible(true);
        }
    }
    
    /**
     * Limpia los campos del formulario y restablece los valores predeterminados.
     */
    private void limpiarFormulario() {
        idField.setText("");
        nombreField.setText("");
        edadSpinner.setValue(1);
        tipoMascotaCombo.setSelectedIndex(0);
        razaField.setText("");
        domesticoCheckBox.setSelected(false);
        duenioIdField.setText("");
        duenioNombreField.setText("");
        duenioTelefonoField.setText("");
        detallesArea.setText("");
        actualizarCamposSegunTipo();
        idField.requestFocus();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
